- name: Add Configurations - kibana.yml
  template: 
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0644
  notify: Restart services

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
  loop:
    - "{{ kibana_log_directory }}"

- name: Copy certificate key for ssl from variable
  copy:
    content: "{{ kibana_ssl_key }}"
    dest: "{{ kibana_ssl_key_path }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0640
  notify: Restart services
  when: kibana_copy_ssl_from_variable

- name: Copy certificate for ssl from variable
  copy:
    content: "{{ kibana_ssl_cert }}"
    dest: "{{ kibana_ssl_cert_path }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0640
  notify: Restart services
  when: kibana_copy_ssl_from_variable

- name: Copy certificate key for ssl from file
  copy:
    src: "{{ kibana_ssl_key }}"
    dest: "{{ kibana_ssl_key_path }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0640
  notify: Restart services
  when: kibana_copy_ssl_from_file

- name: Copy certificate for ssl from file
  copy:
    src: "{{ kibana_ssl_cert }}"
    dest: "{{ kibana_ssl_cert_path }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0640
  notify: Restart services
  when: kibana_copy_ssl_from_file