---

- name: Add reposirtory - Elasticsearch repository for 7.x packages
  yum_repository:
    name: Elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: "https://artifacts.elastic.co/packages/oss-7.x/yum"
    gpgcheck: 1
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    enabled: 1

- name: Add reposiroty - Release RPM artifacts of OpenDistroForElasticsearch
  yum_repository: 
    name: OpenDistroForElasticsearch
    description: Release RPM artifacts of OpenDistroForElasticsearch
    baseurl: https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/
    enabled: 1
    gpgkey: https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
    gpgcheck: 1
    repo_gpgcheck: 1

- name: Install RedHat package
  yum:
    name: "{{ item }}"
    state: present
  notify: Restart services
  loop: "{{ redhat_packages }}"

- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  notify: Restart services
  loop: "{{ redhat_services }}"
